### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by joenye** [joenye/creepy-server#1]
- [x] Create actions "reducer" module
- [ ] Add actions to API response + add action endpoint
- [ ] Add endpoint(s) to allow client to refresh state
- [x] Adopt redux-ducks module format

Cards, stairs, and more to follow.
